// Command xpressgen generates xpress_data_test.go. The plain LZ77
// vectors are produced with an encoder that follows the MS-XCA section
// 2.1.1 pseudocode; the LZ77+Huffman vectors are kept as hand-maintained
// fixtures.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

type vector struct {
	name          string
	input         []byte
	expected      []byte
	huff          bool
	precompressed bool
}

func main() {
	var vecs []vector
	vecs = append(vecs, plainVectors()...)
	vecs = append(vecs, extraPlainVectors()...)
	vecs = append(vecs, sharedHalfByteVector())
	vecs = append(vecs, anchorVector())

	var b strings.Builder
	b.WriteString("// Code generated by tests/xpressgen; DO NOT EDIT.\n")
	b.WriteString("// The plain LZ77 vectors are generated with a spec-faithful\n")
	b.WriteString("// encoder (MS-XCA 2.1.1). The LZ77+Huffman vectors are\n")
	b.WriteString("// hand-maintained fixtures (see tests/xpressgen).\n")
	b.WriteString("package xpress\n\n")
	b.WriteString("import \"bytes\"\n\n")
	b.WriteString("type xpressVector struct {\n")
	b.WriteString("\tname           string\n")
	b.WriteString("\tdata, expected []byte\n")
	b.WriteString("\thuff           bool\n")
	b.WriteString("}\n\n")
	b.WriteString("var xpressVectors = []xpressVector{\n")
	for _, v := range vecs {
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tname: %q,\n", v.name)
		data := v.input
		if !v.precompressed {
			data = encode(v.input)
		}
		b.WriteString("\t\tdata: []byte{")
		for i, x := range data {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "0x%02x", x)
		}
		b.WriteString("},\n")
		b.WriteString("\t\texpected: ")
		b.WriteString(bytesRepeatExpr(v.expected))
		b.WriteString(",\n")
		fmt.Fprintf(&b, "\t\thuff: %v,\n", v.huff)
		b.WriteString("\t},\n")
	}
	// The LZ77+Huffman fixtures predate the generator; splice them in
	// verbatim so the output file is complete.
	huff, err := os.ReadFile(filepath.Join(filepath.Dir(srcFile()), "huffman_vectors.txt"))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	for _, line := range strings.Split(strings.TrimRight(string(huff), "\n"), "\n") {
		b.WriteString(line + "\n")
	}
	b.WriteString("}\n")

	// Resolve the output path relative to this source file so the
	// generator works from any working directory.
	outPath := filepath.Join(filepath.Dir(srcFile()), "..", "..", "xpress", "xpress_data_test.go")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// srcFile returns the path of this source file.
func srcFile() string {
	_, file, _, _ := runtime.Caller(0)
	return file
}

// bytesRepeatExpr renders a repetitive byte slice as a bytes.Repeat call.
func bytesRepeatExpr(b []byte) string {
	for i := 0; i < len(b); i++ {
		u := append([]byte(nil), b[:i+1]...)
		if len(u) > 0 && len(b)%len(u) == 0 {
			ok := true
			for j := 0; j < len(b); j += len(u) {
				if !bytes.Equal(b[j:j+len(u)], u) {
					ok = false
					break
				}
			}
			if ok && len(b)/len(u) > 1 && len(u) <= 16 {
				return fmt.Sprintf("bytes.Repeat([]byte(%q), %d)", u, len(b)/len(u))
			}
		}
	}
	var sb strings.Builder
	sb.WriteString("[]byte{")
	for i, x := range b {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "0x%02x", x)
	}
	sb.WriteString("}")
	return sb.String()
}

// encode matches the MS-XCA 2.1.1 encode pseudocode verbatim.
func encode(data []byte) []byte {
	var out []byte
	flags := uint32(0)
	flagCount := 0
	flagOutPos := 0
	outPos := 0
	inPos := 0
	lastLenHalf := 0

	writeFlags := func() {
		for i := 0; i < 4; i++ {
			out[flagOutPos+i] = byte(flags >> (8 * i))
		}
		flagCount = 0
		flagOutPos = 0
	}
	put := func(x byte) {
		out = append(out, x)
		outPos++
	}

	n := len(data)
	for inPos < n {
		bestLen := 0
		bestOff := 0
		maxLen := n - inPos
		if maxLen > 1<<17 {
			maxLen = 1 << 17
		}
		start := inPos - 8192
		if start < 0 {
			start = 0
		}
		for cand := start; cand < inPos; cand++ {
			l := 0
			for l < maxLen && data[cand+l] == data[inPos+l] {
				l++
			}
			if l > bestLen {
				bestLen = l
				bestOff = inPos - cand
			}
		}
		if bestLen < 3 || inPos+2 >= n {
			// Literal.
			flags <<= 1
			flagCount++
			if flagCount == 1 {
				flagOutPos = outPos
				out = append(out, 0, 0, 0, 0)
				outPos += 4
			}
			put(data[inPos])
			inPos++
			if flagCount == 32 {
				writeFlags()
			}
			continue
		}
		// Match.
		matchLen := bestLen - 3
		matchOff := bestOff - 1
		matchOff <<= 3
		if matchLen < 7 {
			tok := matchOff + matchLen
			put(byte(tok))
			put(byte(tok >> 8))
		} else {
			tok := matchOff | 7
			put(byte(tok))
			put(byte(tok >> 8))
			matchLen -= 7
			if lastLenHalf == 0 {
				lastLenHalf = outPos
				if matchLen < 15 {
					put(byte(matchLen))
				} else {
					put(15)
					goto encodeExtraLen
				}
			} else {
				if matchLen < 15 {
					out[lastLenHalf] |= byte(matchLen << 4)
					lastLenHalf = 0
				} else {
					out[lastLenHalf] |= 15 << 4
					lastLenHalf = 0
					goto encodeExtraLen
				}
			}
			goto afterLen
		encodeExtraLen:
			matchLen -= 15
			if matchLen < 255 {
				put(byte(matchLen))
			} else {
				put(255)
				matchLen += 7 + 15
				if matchLen < 1<<16 {
					put(byte(matchLen))
					put(byte(matchLen >> 8))
				} else {
					put(0)
					put(0)
					put(byte(matchLen))
					put(byte(matchLen >> 8))
					put(byte(matchLen >> 16))
					put(byte(matchLen >> 24))
				}
			}
		afterLen:
			_ = matchLen
		}
		flags = (flags << 1) | 1
		flagCount++
		if flagCount == 32 {
			writeFlags()
		}
		inPos += bestLen
	}
	if flagCount > 0 {
		flags <<= uint(32 - flagCount)
		flags |= (1 << uint(32-flagCount)) - 1
		for i := 0; i < 4; i++ {
			out[flagOutPos+i] = byte(flags >> (8 * i))
		}
	}
	return out
}

func plainVectors() []vector {
	return []vector{
		{
			name:     "Plain0: all literals",
			input:    []byte("GHOST//RECOVER data recovery engineer.\n"),
			expected: []byte("GHOST//RECOVER data recovery engineer.\n"),
		},
		{
			name:     "Plain1: the MS-XCA worked example, 100 copies of abc",
			input:    bytes.Repeat([]byte("abc"), 100),
			expected: bytes.Repeat([]byte("abc"), 100),
		},
		{
			name:     "Plain2: nibble-encoded length (49 copies of P)",
			input:    bytes.Repeat([]byte("P"), 49),
			expected: bytes.Repeat([]byte("P"), 49),
		},
		{
			name:     "Plain3: byte-encoded length (300 copies of A)",
			input:    bytes.Repeat([]byte("A"), 300),
			expected: bytes.Repeat([]byte("A"), 300),
		},
		{
			name:     "Plain4: LE16 length (4002 copies of Q)",
			input:    bytes.Repeat([]byte("Q"), 4002),
			expected: bytes.Repeat([]byte("Q"), 4002),
		},
		{
			name:     "Plain5: two matches in one flag group",
			input:    bytes.Repeat([]byte("abcdefghij"), 30),
			expected: bytes.Repeat([]byte("abcdefghij"), 30),
		},
		{
			name:     "Plain6: shared half-byte between two matches",
			input:    append(bytes.Repeat([]byte("abcdefghij"), 2), bytes.Repeat([]byte("xy"), 12)...),
			expected: append(bytes.Repeat([]byte("abcdefghij"), 2), bytes.Repeat([]byte("xy"), 12)...),
		},
		{
			name:     "Plain7: literal between two shared-nibble matches",
			input:    append(append(bytes.Repeat([]byte("mnop"), 8), 'Z'), bytes.Repeat([]byte("mnop"), 8)...),
			expected: append(append(bytes.Repeat([]byte("mnop"), 8), 'Z'), bytes.Repeat([]byte("mnop"), 8)...),
		},
		{
			name:     "Plain8: LE32 length (70000 copies of W)",
			input:    bytes.Repeat([]byte("W"), 70000),
			expected: bytes.Repeat([]byte("W"), 70000),
		},
		{
			name:     "Plain9: large offset (6000 copies of a 22-byte phrase)",
			input:    bytes.Repeat([]byte("0123456789abcdefghijkl"), 6000),
			expected: bytes.Repeat([]byte("0123456789abcdefghijkl"), 6000),
		},
	}
}

func extraPlainVectors() []vector {
	var v []vector
	// Lengths that land on every nibble value: 11..24 cover nibbles 1..14.
	for l := 11; l <= 24; l++ {
		v = append(v, vector{
			name:     fmt.Sprintf("PlainNib%d: length %d", l-10, l),
			input:    bytes.Repeat([]byte("n"), l),
			expected: bytes.Repeat([]byte("n"), l),
		})
	}
	// Lengths that land on byte values 1..254: 26..279.
	for _, l := range []int{26, 50, 100, 150, 200, 250, 279} {
		v = append(v, vector{
			name:     fmt.Sprintf("PlainByte%d: length %d", l-25, l),
			input:    bytes.Repeat([]byte("b"), l),
			expected: bytes.Repeat([]byte("b"), l),
		})
	}
	return v
}

func sharedHalfByteVector() vector {
	// A literal between two shared-nibble matches: the pending half-byte
	// must survive the literal. Hand-encoded:
	//   flags f1 literal, f2 match(1,11), f3 literal, f4 match(1,12)
	//   match 2's length rides in the high nibble of the byte written by
	//   match 1 (0x01 -> 0x21).
	return vector{
		name: "PlainSharedHalfByteAcrossLiteral",
		input: []byte{
			0xff, 0xff, 0xff, 0x5f,
			0x41,       // 'A'
			0x07, 0x00, // match offset 1, shared-nibble form
			0x21,       // low nibble: length 11; high nibble: length 12 (next)
			0x42,       // 'B'
			0x07, 0x00, // match offset 1, uses high nibble of the byte above
		},
		expected:      append([]byte("AAAAAAAAAAAA"), []byte("BBBBBBBBBBBBB")...),
		precompressed: true,
	}
}

func anchorVector() vector {
	// The classic decompression test vector, also present in the
	// sleuthkit and go-ntfs XPRESS tests.
	input := bytes.Repeat([]byte("A1B2C3D4E5F6G7H8"), 16)
	return vector{
		name:     "Anchor",
		input:    input,
		expected: input,
	}
}
